language: cpp
sudo: required
dist: bionic

jobs:
 include:
  - name: "Build on Linux/gcc"
    os: linux
    compiler: gcc
    script:
     - cd ${TRAVIS_BUILD_DIR}
     - mkdir build && cd build
     - cmake ..
     - make
     - make test
  - name: "Build on Linux/clang"
    os: linux
    compiler: clang
    script:
     - cd ${TRAVIS_BUILD_DIR}
     - mkdir build && cd build
     - cmake ..
     - make
     - make test
  - name: "Build on OS X/gcc"
    os: osx
    compiler: gcc
    script:
     - cd ${TRAVIS_BUILD_DIR}
     - mkdir build && cd build
     - cmake ..
     - make
     - make test
  - name: "Build on OS X/clang"
    os: osx
    compiler: clang
    script:
     - cd ${TRAVIS_BUILD_DIR}
     - mkdir build && cd build
     - cmake ..
     - make
     - make test
  - name: "Run clang-tidy"
    os: linux
    compiler: gcc
    script:
     - cd ${TRAVIS_BUILD_DIR}
     - mkdir build && cd build
     - cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ..
     - make
     - ./../scripts/run_clang_tidy.sh
